### ISSUE TITLE
Request module deprecated?

### ISSUE THREAD

**Issue by MystaraTheGreat** [nwootton/MMM-UKNationalRail#16]
I suspect that this module relies on a deprecated module.  After upgrading my magic mirror core code, I get the following error:

[01.10.2021 18:49.04.563] [ERROR] App threw an error during load
[01.10.2021 18:49.04.568] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-UKNationalRail/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-

**Comment by nwootton** [comment]
As noted in the README, I no longer run a Magic Mirror and this code is no longer supported. Feel free to fork and update as required.
