### ISSUE TITLE
No Longer Working

### ISSUE THREAD

**Issue by diversionsc** [nwootton/MMM-UKNationalRail#2]
Seems as of the start of the month i can no longer get this extension to work.

All i have stuck on my display is "Loading trains"

**Comment by nwootton** [comment]
1) The module hasn’t changed since the last update 5 months ago.
2) I am unable to check the TransportAPI is supporting your specific situation without the information that is listed as required at the bottom of the README in the Troubleshooting section.
3) What changed on your installation?

**Comment by nwootton** [comment]
So I've installed the latest version of the Mirror and the NationalRail module in a dev environment. Both have been running fine since last night with no issues. Transport API is responding via the module and via curl requests. Without further information I'm afraid there is nothing else I can do.

**Comment by nwootton** [comment]
No further information supplied - closing issue
