### ISSUE TITLE
Can't do Arrivals or passes.

### ISSUE THREAD

**Issue by michaeldun123** [nwootton/MMM-UKNationalRail#4]
I've done it with many stations, and you can't do arrivals or passes.

**Comment by nwootton** [comment]
Please see 'Troubleshooting' in the README file. 

There are no references to 'Arrivals' and 'Passes' in the documentation either - are you referring to 'calling_at' or 'called_at'? Both of which do work.
```
https://transportapi.com/v3/uk/train/station/SUR/live.json?app_id=xxxxxxxx&app_key=xxxxxxxxxxxxxxxxxxxxxxx&calling_at=BRS
```
```
https://transportapi.com/v3/uk/train/station/SUR/live.json?app_id=xxxxxxxx&app_key=xxxxxxxxxxxxxxxxxxxxxxx&called_at=THD
```
What you can't do - and this is shown in the TransportAPI is use both 'called_at' & 'calling_at' in the same request.
```
https://transportapi.com/v3/uk/train/station/SUR/live.json?app_id=xxxxxxxx&app_key=xxxxxxxxxxxxxxxxxxxxxxx&called_at=THD&calling_at=BRS
```

**Comment by michaeldun123** [comment]
I was looking at the "Type" part in the readme.md. And I did that in the MMM-UKNationalRail.js, I did arrival on its own, shown none same with pass.

**Comment by nwootton** [comment]
Looks like Transport API have changed their response format to specifically respond to the type format supplied. I'll have to try and fix it at some point.

**Comment by michaeldun123** [comment]
Okay, thanks nwootton.

**Comment by nwootton** [comment]
Quick branch hack

```
git clone -b Issue4 https://github.com/nwootton/MMM-UKNationalRail.git
```

Replace your current Rail module with this branch - see if that works for you.
*BTW, I have NOT used the ```Type``` feature, so I have no idea what the data returned actually represents.*

**Comment by michaeldun123** [comment]
Okay, I shall let you know.

**Comment by michaeldun123** [comment]
Arrivals now work. Not sure about pass

**Comment by michaeldun123** [comment]
Pass shows nothing.

**Comment by nwootton** [comment]
'pass' works here - could be that nothing 'passes' that station without stopping?

![screen shot 2018-08-29 at 14 50 02](https://user-images.githubusercontent.com/7591978/44792054-f8115980-ab9a-11e8-973d-b8de53ef1236.png)
![screen shot 2018-08-29 at 14 50 08](https://user-images.githubusercontent.com/7591978/44792055-f8115980-ab9a-11e8-9e9c-97ec33356511.png)

**Comment by michaeldun123** [comment]
I'm doing Lincoln Central. CRS:LCN. Normally goods pass the station, but it showed nothing. Not even goods.

**Comment by nwootton** [comment]
Running the URL for LCN directly in a browser reports an empty array. So it is working for 'pass'.

```
https://transportapi.com/v3/uk/train/station/LCN/live.json?app_id=xxxxxx&app_key=xxxxxxxxxxxxxx&type=pass
```
