### ISSUE TITLE
Header being replaced by station name

### ISSUE THREAD

**Issue by pmishev** [nwootton/MMM-UKNationalRail#5]
Once the module has loaded, the header (e.g 'Arrivals') is replaced by the station name, so setting a header is essentially useless.
However, what would be great is if the set header could be combined with the station name instead.
So, for example, if my header is `Arrivals from `, it would become `Arrivals from London Victoria`.

I have added the module twice in my config - once showing the departures from my nearest station and once showing the arrivals and it's hard to distinguish between the 2 at the moment

**Comment by nwootton** [comment]
Apologies, for not responding, but I no longer use a MagicMirror, so I've not done anything on this platform for several months. Feel free to fork and make changes you feel are appropriate for your circumstances,
