### ISSUE TITLE
train times do not update

### ISSUE THREAD

**Issue by bachoo786** [nwootton/MMM-UKNationalRail#6]
hello mate

I have got this up and running and have noticed that occasionally the train times wont update for some reason until I restart mm i.e. pm2 restart mm 

Can you please look into this? As it has happened 3 times now on different days.

Thanks.

**Comment by nwootton** [comment]
I no longer use a MagicMirror, so I've not done anything on this platform for several months. In fact the module _hasn't_ been tested against any version greater than v2.4.0. Feel free to fork and make changes you feel are appropriate for your circumstances. 

With reference to the issue you are having, running the mirror until v2.4 I had no instances of the module stopping _except_ when bad data was provided. 

The data displayed by the module comes from a third-party who get their data from the train companies. Neither the module or Transport API can do anything about the train companies providing (or even not providing) quality data.

**Comment by mattdy** [comment]
I had similar issues, I believe this may be fixed by #15
